In [85]:
import json, requests
import string
import re
import gzip
import shutil
import urllib.request 
import pandas as pd
# import imdbpy


# name gender num_times_nominated age_nomination age_when_win

oscars = pd.read_csv("../data/the_oscar_award_corrected.csv")
actors = pd.read_csv("../data/actors.csv")
actress = pd.read_csv("../data/actresses.csv")
# oscars = pd.read_csv("../data/oscar_winners_clean.csv")
# oscars["primaryName"]=oscars["name"]
oscars.loc[oscars['category'].str.contains("ACTOR"), "gender"]='M'
oscars.loc[oscars['category'].str.contains("ACTRESS"), "gender"]='F'

noms = actors.append(actress)
# noms.tail()
nominees = pd.merge(oscars, noms, how='inner', on=['name'])
nominees = nominees[['name','year_film','category_x', 'birthYear', 'ceremonyAge','gender_x', 'winner_x','nconst']]
nominees
# oscars.head()
nominations = nominees.groupby(['name','winner_x', 'gender_x', 'birthYear', 'year_film','category_x']).count().reset_index()
nominations["ceremonyAge"]=nominations['year_film']-nominations['birthYear']

nominations.rename(columns={"nconst": "num_times_nominated", "category_x":"category","winner_x":"winner", "gender_x":"gender"})
nominations
oscars

,year_film,year_ceremony,ceremony,category,name,film,winner,gender
0,1927,1928,1,ACTOR,Richard Barthelmess,The Noose,False,M
1,1927,1928,1,ACTOR,Emil Jannings,The Last Command,True,M
2,1927,1928,1,ACTRESS,Louise Dresser,A Ship Comes In,False,F
3,1927,1928,1,ACTRESS,Janet Gaynor,7th Heaven,True,F
4,1927,1928,1,ACTRESS,Gloria Swanson,Sadie Thompson,False,F
...,...,...,...,...,...,...,...,...
10415,2020,2021,93,DIRECTING,Chloé Zhao,Nomadland,True,NaN
10416,2020,2021,93,DIRECTING,Thomas Vinterberg,Another Round,False,NaN
10417,2020,2021,93,DIRECTING,David Fincher,Mank,False,NaN
10418,2020,2021,93,DIRECTING,Lee Isaac Chung,Minari,False,NaN
10419,2020,2021,93,DIRECTING,Emerald Fennell,Promising Young Woman,False,NaN